source: pages
destination: tmp

title: UI Kit
description: Premium and Open Source dashboard template with responsive and high quality UI.

debug: true

plugins:
- jekyll-random
- jekyll-tidy
- jekyll-timeago
- jekyll-redirect-from
- jekyll-include-cache

keep_files:
- css/ui-kit.css
- css/dark.css
- css/rtl.css
#- js/ui-kit.js

markdown: kramdown
highlighter: rouge

kramdown:
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    css_class: ''
    span:
      line_numbers: false

jekyll_tidy:
  compress_html: false
  ignore_env: development


collections:
  docs:
    output: true
  changelog:
    output: false

defaults:
  -
    scope:
      type: pages
    values:
      layout: default
  -
    scope:
      type: docs
    values:
      layout: docs


colors:
  blue:
    hex: '#467fcf'
    name: Blue
  azure:
    hex: '#45aaf2'
    name: Azure
  indigo:
    hex: '#6574cd'
    name: Indigo
  purple:
    hex: '#a55eea'
    name: Purple
  pink:
    hex: '#f66d9b'
    name: Pink
  red:
    hex: '#cd201f'
    name: Red
  orange:
    hex: '#fd9644'
    name: Orange
  yellow:
    hex: '#f1c40f'
    name: Yellow
  lime:
    hex: '#7bd235'
    name: Lime
  green:
    hex: '#5eba00'
    name: Green
  teal:
    hex: '#2bcbba'
    name: Teal
  cyan:
    hex: '#17a2b8'
    name: Cyan
  gray:
    hex: '#868e96'
    name: Gray
  dark:
    hex: '#354051'
    name: Dark

variants:
  - name: success
    icon: check
  - name: info
    icon: info
  - name: warning
    icon: alert-triangle
  - name: danger
    icon: x-octagon

socials: [facebook, twitter, google, youtube, vimeo, dribbble, github, instagram, pinterest, vk, rss, flickr, bitbucket]

months_short: ['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec']
months_long: ['January', 'Febuary', 'Mar', 'Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec']
