title: tabler.io
description: tabler.io - a responsive, flat and full featured admin template
base_color: '#cc0000'

collections:
  docs:
    output: true

defaults:
  - scope:
      path: ""
      type: docs
    values:
      layout: docs

author:
   name: codecalm.net
   url: https://codecalm.net

plugins:
  #- jekyll-tidy
  - jekyll-contentblocks
  #- jekyll-toc

exclude:
  - buddy.yml
  - package.json
  - gulpfile.js
  - start.sh
  - Gemfile
  - Gemfile.lock
  - .git
  - .idea
  - .gitignore
  - node_modules/
  - .DS_Store
  - .sass-cache/
  - .asset-cache/
  - assets/scss/*
  - assets/plugins/**/*.scss
  - push-to-repo.sh

markdown: kramdown
highlighter: rouge

kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    css_class: ''
    span:
      line_numbers: false

toc:
  min_level: 2
  max_level: 3

jekyll_tidy:
  compress_html: false
  ignore_env: development

colors:
  blue: '#467fcf'
  azure: '#45aaf2'
  indigo: '#6574cd'
  purple: '#a55eea'
  pink: '#f66d9b'
  red: '#e74c3c'
  orange: '#fd9644'
  yellow: '#f1c40f'
  lime: '#7bd235'
  green: '#5eba00'
  teal: '#2bcbba'
  cyan: '#17a2b8'
  gray: '#868e96'
  gray-dark: '#343a40'

theme-colors:
  primary: '#467fcf'
  secondary: '#868e96'
  success: '#38c172'
  info: '#17a2b8'
  warning: '#f8b700'
  danger: '#f90049'
  light: '#f8f9fa'
  dark: '#343a40'

google-maps-key: AIzaSyBEJy4UvF-JfcNciWlvlznyDlUckcspiD4
google-maps-url: https://maps.googleapis.com/maps/api/js?key=AIzaSyCOJwXN0eoyeFZ3cYtGzPLFw8zGhQ750Xk