source: pages
destination: tmp

title: UI Kit
description: Premium and Open Source dashboard template with responsive and high quality UI.

debug: true

plugins:
- jekyll-random
- jekyll-tidy
- jekyll-timeago
- jekyll-redirect-from

keep_files:
- css/ui-kit.css
- css/dark.css
- css/rtl.css
#- js/ui-kit.js

markdown: kramdown
highlighter: rouge

kramdown:
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    css_class: ''
    span:
      line_numbers: false

jekyll_tidy:
  compress_html: false
  ignore_env: development


collections:
  docs:
    output: true
  changelog:
    output: false

defaults:
  -
    scope:
      type: pages
    values:
      layout: default
  -
    scope:
      type: docs
    values:
      layout: docs

