languageCode:           "en"
title:                  "Tabler"
baseURL:                "https://tabler.io"
enableInlineShortcodes: true

enableRobotsTXT:        true
metaDataFormat:         "yaml"
disableKinds:           ["404", "home", "taxonomy", "taxonomyTerm", "RSS"]

publishDir:             "_gh_pages"
archetypeDir:           "site/archetypes"
contentDir:             "site/pages"
assetDir:               "site/assets"
staticDir:              "site/static"
layoutDir:              "site/layouts"

params:
  colors:
    blue:
      hex: '#467fcf'
      name: Blue
    azure:
      hex: '#45aaf2'
      name: Azure
    indigo:
      hex: '#6574cd'
      name: Indigo
    purple:
      hex: '#a55eea'
      name: Purple
    pink:
      hex: '#f66d9b'
      name: Pink
    red:
      hex: '#cd201f'
      name: Red
    orange:
      hex: '#fd9644'
      name: Orange
    yellow:
      hex: '#f1c40f'
      name: Yellow
    lime:
      hex: '#7bd235'
      name: Lime
    green:
      hex: '#5eba00'
      name: Green
    teal:
      hex: '#2bcbba'
      name: Teal
    cyan:
      hex: '#17a2b8'
      name: Cyan
    gray:
      hex: '#868e96'
      name: Gray
    dark:
      hex: '#354051'
      name: Dark

  variants: [primary, secondary, success, info, warning, danger, dark]
  socials: [facebook, twitter, google, youtube, vimeo, dribbble, github, instagram, pinterest, vk, rss, flickr, bitbucket]

  months_short: ['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec']
  months_long: ['January', 'Febuary', 'Mar', 'Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec']


  docs-menu:
  - title: Getting started
    pages: [index]
  - title: Components
    pages: [avatars, badges, buttons, carousel, spinners, steps, toasts, tooltips, typography]
