name: Jekyll site CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v1
      
    - name: Wait for Netlify
      uses: JakePartusch/wait-for-netlify-action@v1.0
      with:
        site_name: tabler

