name: Tests

on: [push, pull_request]

jobs:
  run:
    name: Node ${{ matrix.node }}
    runs-on: ubuntu-latest
    
    strategy:
      fail-fast: false
      matrix:
        node: [10, 12]

    steps:
      - name: Clone repository
        uses: actions/checkout@v1
        
      - name: Set Node.js version
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}
          
      - name: Set Ruby version
        uses: actions/setup-ruby@v1
        with:
          ruby-version: '2.4.x'
          
      - name: Set up Bundler
        run: gem install bundler -v "~> 1.17"
          
      - run: ruby --version
      - run: gem --version
      - run: bundle --version
      - run: node --version
      - run: npm --version
        
      - name: Install npm dependencies
        run: npm install

      - name: Install bundler dependencies
        run: bundle install --deployment --jobs=3 --retry=3 --clean
        
      - name: Run bundlesize
        run: npm run bundlesize
